# Generated by Django 3.0.3 on 2020-02-25 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='approvals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('dependants', models.IntegerField()),
                ('applicantincome', models.IntegerField()),
                ('coapplicantincome', models.IntegerField()),
                ('loanamt', models.IntegerField()),
                ('loanterm', models.IntegerField()),
                ('credithistroy', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=15)),
                ('married', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=15)),
                ('graduatededucation', models.CharField(choices=[('Graduate', 'Graduate'), ('Not_Graduate', 'Not_Graduate')], max_length=15)),
                ('selfemployed', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=15)),
                ('area', models.CharField(choices=[('Rural', 'Rural'), ('Urban', 'Urban')], max_length=15)),
            ],
        ),
    ]
