# Generated by Django 3.0.3 on 2020-02-25 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvals',
            name='applicantincome',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='approvals',
            name='coapplicantincome',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='approvals',
            name='credithistroy',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='approvals',
            name='dependants',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='approvals',
            name='loanamt',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='approvals',
            name='loanterm',
            field=models.IntegerField(default=0),
        ),
    ]
